// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.DA.EF;

namespace Ordering.DA.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20211231063151_OrderDb")]
    partial class OrderDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ordering.DA.Entities.Delivery", b =>
                {
                    b.Property<string>("DeliveryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameReceiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNameReceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryID");

                    b.ToTable("Deivery");

                    b.HasData(
                        new
                        {
                            DeliveryID = "61b6f8cfbc9a67e61c8ddf2e",
                            Address = "số 1 Võ Văn Ngân",
                            CustomerID = "61cea2f375e10dd236f9de06",
                            Email = "181330@gmail.com",
                            FirstNameReceiver = "Viet",
                            LastNameReceiver = "Lam",
                            PhoneNo = "0944329423"
                        });
                });

            modelBuilder.Entity("Ordering.DA.Entities.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("OrderID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("PaymentID");

                    b.ToTable("SaleOrder");

                    b.HasData(
                        new
                        {
                            OrderID = "61b6f8e8a13fc9a1ba108bf3",
                            CustomerID = "61cea2f375e10dd236f9de06",
                            CustomerName = "Viet",
                            DeliveryID = "61b6f8cfbc9a67e61c8ddf2e",
                            Gender = 0,
                            IsDelete = false,
                            OrderDate = new DateTime(2021, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentID = "61b6f8c78909657b658f6887",
                            TotalAmount = 100000.0
                        });
                });

            modelBuilder.Entity("Ordering.DA.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderDetailID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<double>("VAT")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.ToTable("SaleOrderDetail");

                    b.HasData(
                        new
                        {
                            OrderDetailID = "96a0dd33-9771-4d77-b6fe-4219d75d79d7",
                            IMEI = "312312321312",
                            OrderID = "61b6f8e8a13fc9a1ba108bf3",
                            ProductName = "Itel 33",
                            Quantity = 1,
                            SalePrice = 50000.0,
                            VAT = 0.10000000000000001
                        },
                        new
                        {
                            OrderDetailID = "af11ae72-75f9-49d9-81e0-a9ea12417c01",
                            OrderID = "61b6f8e8a13fc9a1ba108bf3",
                            ProductName = "Tai nghe Sony",
                            Quantity = 1,
                            SalePrice = 50000.0,
                            VAT = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("Ordering.DA.Entities.Payment", b =>
                {
                    b.Property<string>("PaymentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            PaymentID = "61b6f8c78909657b658f6887",
                            CVV = "123",
                            CardName = "ABC",
                            CardNo = "1221313",
                            CustomerID = "61cea2f375e10dd236f9de06",
                            Expiration = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = ""
                        });
                });

            modelBuilder.Entity("Ordering.DA.Entities.Order", b =>
                {
                    b.HasOne("Ordering.DA.Entities.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ordering.DA.Entities.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Ordering.DA.Entities.OrderDetail", b =>
                {
                    b.HasOne("Ordering.DA.Entities.Order", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ordering.DA.Entities.Delivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ordering.DA.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Ordering.DA.Entities.Payment", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
